name: abo_glumbo_bbk
description: "A new Flutter project."
publish_to: "none"
version: 1.2.0+2
environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.8
  dotted_border: ^3.1.0
  dio: ^5.8.0+1
  equatable: ^2.0.8
  firebase_analytics: ^12.0.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  firebase_messaging: ^16.0.0
  firebase_storage: ^13.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc: ^9.2.1
  flutter_local_notifications: ^19.4.0
  flutter_localizations:
    sdk: flutter
  flutter_polyline_points: ^3.0.1
  flutter_svg: ^2.2.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_fonts: ^8.0.2
  google_maps_flutter: ^2.12.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.4.0
  flutter_dotenv: ^5.2.1

  image_cropper: ^12.1.1
  pdf: ^3.12.0
  printing: ^5.14.3

  image_picker: ^1.1.2
  file_picker: ^8.1.6
  intl: ^0.20.2
  local_auth: ^2.3.0
  location: ^8.0.1
  pay: ^3.2.1
  smooth_page_indicator: ^2.0.1
  table_calendar: ^3.2.0
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  video_player: ^2.10.0
  shimmer: ^3.0.0
  firebase_database: ^12.1.0
  sms_autofill: ^2.4.1
  uuid: ^4.5.1
  font_awesome_flutter: ^10.9.1
  pinput: ^6.0.2
  material_symbols_icons: ^4.2951.0
  ntp: ^2.0.0
  arabic_reshaper: ^0.0.1

dev_dependencies:
  flutter_launcher_icons: "^0.14.1"
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/images/app_icon.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/map_styles/
    - assets/images/
    - assets/
    - assets/icons/
    - .env

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-VariableFont_opsz,wght.ttf


flutter_gen:
  synthetic-package: false
